### ISSUE TITLE
Support for `lognormal` delayDistribution

### ISSUE THREAD

**Issue by andymac4182** [beltram/stubr#476]
I am trying to use wiremocks to load test a service. It would be great if `stubr` supported `lognormal` in `delayDistrobution` to enable better emulation of delays.

```
"delayDistribution": {
      "type": "lognormal",
      "median": 40,
      "sigma": 2
    }
```

**Comment by beltram** [comment]
That sounds like a nice addition, will have a look at it

**Comment by beltram** [comment]
Done in [0.6.1](https://github.com/beltram/stubr/releases/tag/0.6.1)
