### ISSUE TITLE
Handlebars in the bodyFileName

### ISSUE THREAD

**Issue by nicodelbaere** [beltram/stubr#478]
[Wiremock 🐌 feature](https://wiremock.org/3.x/docs/response-templating/#templated-body-file) which gives the possibility to use Handlebars in the `bodyFileName` field is useful to dynamically change the file name reference in function of URL segments and/or query parameters and/or headers...

It will be greet to add the feature in Stubr 🚀

**Comment by beltram** [comment]
Dear @nicodelbaere 👋🏼 , please find this in the [0.6.2](https://github.com/beltram/stubr/releases/tag/0.6.2).
