### ISSUE TITLE
Add Handlebars `replace` for string

### ISSUE THREAD

**Issue by nicodelbaere** [beltram/stubr#479]
The handlebars is really helpful to create some stubs.
Wiremock use some [libraries](https://wiremock.org/3.x/docs/response-templating/#handlebars-helpers) that already have a lot of handlebars helpers.

It's will be great to have more helper in Stubr particularly the string [replace](https://github.com/jknack/handlebars.java/blob/1ca4f1ba22680cc313e23ca709f24decb9990316/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java#L467) from the [string helpers](https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java) library.

**Comment by beltram** [comment]
Dear @nicodelbaere 👋🏼 , please find this in the [0.6.2](https://github.com/beltram/stubr/releases/tag/0.6.2).  

I just covered the `replace` helper you requested, having all string helpers supported is a bit more work. Feel free to open new issues with the ones you need

**Comment by nicodelbaere** [comment]
Hi @beltram ,
Sure you can't cover all features of all the handlebars libraries added in Wiremock 🤯 .
Thank you ! 👌
